create SCHEMA IF NOT EXISTS wholesalestore;
SET SCHEMA wholesalestore1;
create TABLE wholesalestore1.SPRING_SESSION (
PRIMARY_ID CHAR(36) NOT NULL,
SESSION_ID CHAR(36) NOT NULL,
CREATION_TIME BIGINT NOT NULL,
LAST_ACCESS_TIME BIGINT NOT NULL,
MAX_INACTIVE_INTERVAL INT NOT NULL,
EXPIRY_TIME BIGINT NOT NULL,
PRINCIPAL_NAME VARCHAR(100),
CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);
create UNIQUE INDEX SPRING_SESSION_IX1 ON wholesalestore1.SPRING_SESSION (SESSION_ID);
create INDEX SPRING_SESSION_IX2 ON wholesalestore1.SPRING_SESSION (EXPIRY_TIME);
create INDEX SPRING_SESSION_IX3 ON wholesalestore1.SPRING_SESSION (PRINCIPAL_NAME);
create TABLE wholesalestore1.SPRING_SESSION_ATTRIBUTES (
SESSION_PRIMARY_ID CHAR(36) NOT NULL,
ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
ATTRIBUTE_BYTES BLOB NOT NULL,
CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES wholesalestore1.SPRING_SESSION(PRIMARY_ID) ON delete CASCADE
);